### ISSUE TITLE
RSS feed for blog

### ISSUE THREAD

**Issue by alexkingorg** [spolu/breach_core#101]
I'd like to follow your blog, please consider adding an RSS feed.

**Comment by hoschi** [comment]
me too :+1:

**Comment by bentomas** [comment]
I as well!

**Comment by spolu** [comment]
http://breach.cc/feed.xml works for you guys?

**Comment by alexkingorg** [comment]
Works great here - thanks!

(closing)

**Comment by hoschi** [comment]
in Feedly I must add "http://breach.cc/feed.xml" to get this working. If you want to have auto discover, you should it add along the "http://breach.cc/blog/" path instead (just a guess).

**Comment by alexkingorg** [comment]
You'd want to add something like this to the HTML output:

`<link rel="alternate" type="application/rss+xml" title="Breach Blog" href="http://breach.cc/feed.xml" />`
