### ISSUE TITLE
Proper Handling of C Binding addons with Gyp.

### ISSUE THREAD

**Issue by miketheprogrammer** [spolu/breach_core#105]
Not sure why it is, but as I am trying to use native addons to create modules, the install fine as long as they support 0.11.14, but it states the following errors. I know node-webkit had its own nw-gyp. Not sure what needs to be done here, but it would be great to have the ability to use native addons. I would be happy to work on a PR if you or anyone could point me in the right direction.

Maybe it is just because we are on unstable 0.11.14. As well, you have to have node in your $PATH to run the npm node-gyp.

[2014-07-11T20:01:42.203Z] *********************************************
[2014-07-11T20:01:42.204Z] ERROR: dlopen(/Users/mhernandez/projects/breach_mod_terminal/node_modules/nan-bcrypt/build/Release/bcrypt_lib.node, 1): no suitable image found.  Did find:
[2014-07-11T20:01:42.204Z]  /Users/mhernandez/projects/breach_mod_terminal/node_modules/nan-bcrypt/build/Release/bcrypt_lib.node: mach-o, but wrong architecture
[2014-07-11T20:01:42.204Z] *********************************************
[2014-07-11T20:01:42.206Z] Error: dlopen(/Users/mhernandez/projects/breach_mod_terminal/node_modules/nan-bcrypt/build/Release/bcrypt_lib.node, 1): no suitable image found.  Did find:
[2014-07-11T20:01:42.206Z]  /Users/mhernandez/projects/breach_mod_terminal/node_modules/nan-bcrypt/build/Release/bcrypt_lib.node: mach-o, but wrong architecture
[2014-07-11T20:01:42.206Z]     at Error (native)
[2014-07-11T20:01:42.206Z]     at Module.load (module.js:349:32)
[2014-07-11T20:01:42.206Z]     at Function.Module._load (module.js:305:12)
[2014-07-11T20:01:42.206Z]     at Module.require (module.js:357:17)
[2014-07-11T20:01:42.206Z]     at require (module.js:373:17)
[2014-07-11T20:01:42.206Z]     at bindings (/Users/mhernandez/projects/breach_mod_terminal/node_modules/nan-bcrypt/node_modules/bindings/bindings.js:76:44)
[2014-07-11T20:01:42.206Z]     at Object.<anonymous> (/Users/mhernandez/projects/breach_mod_terminal/node_modules/nan-bcrypt/bcrypt.js:3:35)
[2014-07-11T20:01:42.206Z]     at Module._compile (module.js:449:26)
[2014-07-11T20:01:42.206Z]     at Object.Module._extensions..js (module.js:467:10)
[2014-07-11T20:01:42.206Z]     at Module.load (module.js:349:32)
[2014-07-11T20:01:42.206Z]     at Function.Module._load (module.js:305:12)
[2014-07-11T20:01:42.206Z] ---------------------------------------------

**Comment by spolu** [comment]
I'm no expert at all but I think part of node 0.11 work is to solve that need for a specific image (in particular with the changes made to the v8 API). Any nodeJS expert around here to shed some light on that?

Otherwise we'll have to do as node-webkit I presume.

**Comment by miketheprogrammer** [comment]
So it was simply a problem of architecture. node-gyp defaults to the architecture of the current node on your PATH. I edited it to use the correct architecture and now I get.

dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/mhernandez/projects/breach_mod_terminal/node_modules/nan-bcrypt/build/Release/bcrypt_lib.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/mhernandez/projects/breach_mod_terminal/node_modules/nan-bcrypt/build/Release/bcrypt_lib.node
  Expected in: dynamic lookup

---

This may just be an issue with 0.11.14. Im gonna ask Rvagg for help.

**Comment by spolu** [comment]
The module you're building may not be compliant with v8's headers in 0.11.14?

**Comment by miketheprogrammer** [comment]
Nope it use latest nan.h so its def good and successfully compiles. Here are some considerations below, and I will continue looking into it as well.

Yea, it was definitely not ideal to fork at 0.11.14. Would have been best to for @ 0.10.x, or 0.11.13
No it is. It uses nan.h. Its a problem with trying to mix and match too many things.
1. 0.11.14 is a pre as in (0.11.14-pre). node-gyp does not compile for prebuilds
- Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
  1. Forking it seems to have removed that pre flag, and allows compilation.
  2. This could backfire down the line, because maybe pre builds are not compiled the same way as release builds?
  3. Of course with this in mind, the npm module will have to be updated to use the correct architecture for each build. 
  4. 

I may try to do a complete build of ExoBrowser, Breach and Chromium from scratch with Node 0.11.13 tonight or tomorrow.

Maybe that will shed some light.

---- Quick Edit, - I dont understand why socket.io and engine.io which use WS  work.
ws is also a native binding, but for some reason it works. I have to research the differences.

**Comment by spolu** [comment]
The nodeJS version is defined by the version of v8 in the chromium branch vs the nodeJS one.

And it's not a fork of course otherwise that would be a nightmare to maintain it's just a branch on top of nodeJS master.

**Comment by miketheprogrammer** [comment]
It seems that WS is falling back to a non C version bufferutil.fallback.js. That would explain why that socket.io and engine.io work.

I am assuming that, because the two binaries are different, dynamic linking fails. Because with ExoBrowser you are linking Node directly into the binary. Please let me know if I am correct, seems like your expertise is C and C++.

Basically, I think we need to create a gyp wrapper, that instead links to the Breach binary?

The main problem making sure NODE_MODULE is exposed in the breach binary and making sure that that symbol is what gets linked. Currently node-gyp links against src's in ~/.node-gyp/

**Comment by miketheprogrammer** [comment]
node_module_register is an EXTERN C . It is not statically linked, rather it is set to dynamic linking by node-gyp I assume. Because of the way ExoBrowser, includes the node src and runs its own Node Thread, I believe that somehow this symbol is lost in the abstraction. node_module_register is called by NODE_MODULE which is in node.h. So compilation occurs fine, however linking, fails, because the dynamic linker i guess cannot find the node object, dll, library, what have you

**Comment by miketheprogrammer** [comment]
@spolu I am working on building ExoBrowser from source now. According to https://github.com/rogerwang/node-webkit/wiki/Using-Node-modules#3rd-party-modules-with-cc-addons 

it makes sense that the reason the symbol is missing is because the module was not built with ExoBrowser ABI in mind. Again I am assuming the target should be the ExoBrowser abi and not Breach because Exo is where node lies.

If I can figure this out ill contribute any code and findings, in my opinion allowing users to access native syscalls and libraries through module ecosystem is essential to a vibrant experience of new technology.

**Comment by spolu** [comment]
Completely agreed. And if you can generate that images for node-gyp that would be totally awesome!

With these images available could we use them automatically from Breach when running npm install internally. I guess yes.

That would require to download them or ship them along thoug...

**Comment by miketheprogrammer** [comment]
There are alot of questions, and variables and I am not even sure where to start. Im focusing a building Exo right now. The key is to somehow target the addons for compilation against either the sources from Exo, or the sources included in in third_party/node. However I already tried compiling the node addons with a target of breach/node, which ended up with the same missing symbol error.

Its gonna be alot of trial and error I think.

And no, the point of this is that we wont have to ship anything. We can dynamically link modules as runtime if we can get this working. That would mean being able to expose syscalls and other binaries in userland.

**Comment by miketheprogrammer** [comment]
@spolu I think you have way more experience than I with C/C++. Currently I believe the way the node is included in Exo does not allow for linking. EXTERN C registers for linking time. So far it seems node-webkit is not too different from Exo, in that it uses a similar chromium build style. All nw-gyp does is download different header files (the nodejs header files used for that distro of nw). 

I have tried doing similar however still get the symbol error. so i think the issue lies in the build process.

**edit, EXTERN C also only works in the same namespace, but that shouldnt be a problem.

**Comment by miketheprogrammer** [comment]
Logging more Research here for the future verbosity: (These symbols are at three different locations, but that should not matter to a dynamic linker i think). But this proves that the symbol _node_module_register is definitely exposed

 nm ExoBrowser | grep node_module_register
000286c0 t _node_module_register

nm /usr/local/bin/node | grep node_module_register
0000000100008d3d T _node_module_register

nm Breach | grep node_module_register
00009ef0 t _node_module_register

**Comment by miketheprogrammer** [comment]
AHHHHH, i think I know. with the node binary, the symbol is global(T) whereas with the other binaries the symbol is local(t)

**Comment by miketheprogrammer** [comment]
how does chromium handle the build of third_party/\* . I am tying to understand how it might be being linked such that the scope of the symbols is localized.

**Comment by miketheprogrammer** [comment]
I dont really know how to get this working. I am pretty stumped. Static vs. Dynamic shouldnt really matter, node webkit builds with static library. We may have to force WholeArchive linking for linux and osx, ill try that after my chromium build finishes.

Other than the aforementioned, The only option I can think is trying to embed nodejs into the exo build process rather than linking it in as a library. That would then make exo just like a nodejs executable.

If that succeeds we can figure out a best practice for doing that.

**Comment by lloydwatkin** [comment]
I'd suggest looking at `nan` by @rvagg which abstracts v8 API changes between node versions.

**Comment by miketheprogrammer** [comment]
@lloydwatkin I use nan in several projects. However nan, does not help here. This ticket is about figuring out how to make native third party modules able to dynamically link to the executable at runtime. however, nan, or the NAL which will be part of Node 1.0 should be used in all third party modules. 

@spolu what was your reasoning for force_modules.h, why is that necessary, I ask because the leader of node-webkit wrote back to me and he does the same thing, as well he does the --WholeArchive linker flag. He said force_modules was a hack to make it work on windows.

@rvagg , hey I know this isnt really your domain, however I thought you might have some knowledge that could help us figure out how to expose the symbol node_module_register globally. It seems our current linking phase and build process causes it to become local(hidden) which means third party modules cannot dynamically bind.

**Comment by spolu** [comment]
@miketheprogrammer the compiler on OSX or linux (not sure which one anymore) would remove the symbols as an optiomization. Maybe you can add your missing symbols there!

**Comment by miketheprogrammer** [comment]
Ahh, yes, and i think that is why @rogerwang uses 

In framework:
'xcode_settings': { 'OTHER_LDFLAGS': [ '-Wl,-force_load,libnode.a' ], }, 

In executable:
        ['OS == "linux"', {
          'ldflags': [
            '-Wl,--whole-archive', 'obj/third_party/node/libnode.a', '-Wl,--no-whole-archive' ],
        }],

I am hoping after my chromium build is done, i can test those new settings and maybe they will expose the symbol globally. I know absolutely zero about linkers and compilers, well not zero, but definitely not enough.

**Comment by spolu** [comment]
I had a bunch of issues with `--whole-archive` this is the reason why it's not in the gyp file for the ExoBrowser.... But I guess you can add symbols to the `force_modules` file?

**Comment by miketheprogrammer** [comment]
@spolu, I dont know if that would work. node_module_register is already an extern "c" unmangled symbol, it is definitely present in the final executable, its visibility is local however. So when the Dynamic Linker, on mac (Dyld), on linux something else,  looks for the symbol it cannot find it.
All i need to do is somehow get that lowercase t to be an UpperCase T and all will be fine. But I dont know how heh. Maybe I can find an expert i can pay a small amount who can figure it out.

**edit, just tried the wholearchive attempt, that did not work, however build succeeded at least.

**Comment by spolu** [comment]
@miketheprogrammer we'll eventually find a solution don't worry. I'm even exploring building breach entirely as a node module thanks to @zcbenz's https://github.com/brightray/brightray.

That would solve the entire problem altogether :)

I'll try to experiment with that and see how it goes.

**Comment by spolu** [comment]
BTW: See http://breach.cc/2014/07/15/next-steps-for-breach.html for some details on related subjects!

**Comment by miketheprogrammer** [comment]
@spolu I was actually contemplating that. Breach as a node_module. Whatever you decide to do I am sure it will be good. In the mean time, I am learning a fair amount so i will continue trying some things.

If you decide to go the node module route I believe I can help significantly and lighten the load.

**Comment by spolu** [comment]
@miketheprogrammer I'll try to free some cycle to discover if that's doable relatively easily. If it's the case we can kick it together fairly efficiently! :)

**Comment by miketheprogrammer** [comment]
@spolu only problem with having it as a node module is you can lose the delieverability aspect of reaching users that don't have alot of computer skills or engineering experience. There may still be ways package it nicely however.

Of course there is also the idea of embedding it directly in NodeJS with as a core module and running a fork that contains that. In that case you could package the node executable, with a breach shell and run it that way, but alas I am sure you have more pressing concerns and those cases are highly hypothetical.

**Comment by spolu** [comment]
packageability is important but I guess we build a nicely packaged version on each platform with nodeJS bundled. no?

**Comment by miketheprogrammer** [comment]
@spolu I do believe that would be possible. Just package the NodeJS bundle, however i think that may be only possible in the example where we embed breach directly into nodejs.

**Comment by spolu** [comment]
why not in the case where Breach is just a npm module with native bindings?

**Comment by miketheprogrammer** [comment]
Hmm actually should be able to do it easily as well.

**Comment by spolu** [comment]
@miketheprogrammer started playing with Brightray / libchromiumcontent
We can definitely base future release of the ExoBrowser on top of Brightray and I'm fairly optimistic as to running bundling the whole thing as a native node module... I'll create a new issue and branch on the exo_browser repository. 

The initial experimentation would be to run the brightray example as a native module and make at least one API call go through from JS.

**Comment by miketheprogrammer** [comment]
Ill work on it. I have some other native module responsibilities as well.

**Comment by spolu** [comment]
@miketheprogrammer checkout http://github.com/spolu/node-shell

Almost there

**Comment by miketheprogrammer** [comment]
@spolu I couldnt even get through the brightray build on osx unfortunately. Complaining about no xcode project. But from the look of your code it looks very promising.

**Comment by spolu** [comment]
Try checking it out and running npm install... Though I only tested it on Linux for now

**Comment by miketheprogrammer** [comment]
@spolu Nice build, screwed up on some info plist copy in gyp-mac-tool. But Im sure you or I can figure it out. Too tired to hack away right now (east coast here). But this looks nice. Thank you for all your hard work on this.

**Comment by miketheprogrammer** [comment]
Closing this ticket. With the latest movements this project has taken this is no longer a concern and full support for node native addons is available.
