### ISSUE TITLE
Configure Modules blocks page

### ISSUE THREAD

**Issue by JamoBox** [spolu/breach_core#106]
When selecting 'Configure Modules' on the context menu, it opens on the same page as the currently opened tab and does not provide a way of getting back to the page the user was on.
Perhaps a clean solution would be for the Configure Modules page open in its own tab rather than in the one currently being viewed.

**Comment by spolu** [comment]
Yep totally agreed.
Marking that as a bug

**Comment by brayniverse** [comment]
I could have a go at preparing a PR to fix this bug.

**Comment by spolu** [comment]
:+1: make sure to make the new tab visible as there may not be any tabbing system available...

**Comment by brayniverse** [comment]
Yea I was looking into mod_strip for a hint on how to actually add a new tab. Because I can add tabs etc through the core_tabs API but will mod_strip detect the new tab and add it to the UI?

**Comment by brayniverse** [comment]
@spolu How can I see what `common.log` writes to?

**Comment by t-lutz** [comment]
status -> accepted
assigned -> t-lutz

**Comment by t-lutz** [comment]
status -> code review & validation
assigned -> @spolu
