### ISSUE TITLE
Extract devtools from mod_strip

### ISSUE THREAD

**Issue by RobinMalfait** [spolu/breach_core#107]
I think that you need to strip the devtools part from mod_strip.

Think about the single responsibility principle :)

**Comment by spolu** [comment]
+1

**Comment by miketheprogrammer** [comment]
@RobinMalfait Seems like a good thing to submit a PR for, so far seems like @spolu is the only core dev, so we need to contribute where we can. Refactoring and pulling things out into another module seems like a great way to get to know the code base. :)

**Comment by spolu** [comment]
Agreed!

**Comment by RobinMalfait** [comment]
Agreed, but I won't do it atm :p

**Comment by jonathan-reisdorf** [comment]
I have made a PR for this: https://github.com/breach/mod_strip/pull/65
As this is my first PR here, please discuss/comment ;)

**Comment by spolu** [comment]
Closed by breach/mod_strip#65
