### ISSUE TITLE
Search bar wipes search term on focus lost

### ISSUE THREAD

**Issue by JamoBox** [spolu/breach_core#111]
There is a minor bug when typing a search in the URL bar, if the window loses focus the search term is wiped and set back to an empty box if on a blank page, or if on a page the page's URL.
The search term should persist until the user either cancels it by clicking elsewhere on the page or hitting escape. This is mainly down to intuitiveness, so perhaps it's not so much as a bug but a feature request.

**Comment by spolu** [comment]
@JamoBox can you file this on https://github.com/breach/mod_strip ? Thanks!
