### ISSUE TITLE
Typo in welcome messages

### ISSUE THREAD

**Issue by sdaitzman** [spolu/breach_core#112]
"By default, Breach will be gathering and sending anonymized usage statistics to help us detect issues and required improvements. The stats only include generic event types (no URL, no personnal data) and they are sent to Google Analytics. Obviously, usage stats aggregation is also provided by a module! You can opt-in/opt-out at anytime simply by adding or removing the module `breach/mod_stats`"

Personnal should be changed to personal.

**Comment by spolu** [comment]
Hi thanks for the bug report!

This has already been fixed in a separate pull request... Not package yet in a new version though.
