### ISSUE TITLE
Context menu is not contexual

### ISSUE THREAD

**Issue by JamoBox** [spolu/breach_core#115]
The content of the context menu does not change depending on where/what is being right-clicked. For example, if I highlight some text and right-click, I do not get any options for copying, printing, searching, etc, I just get the same context menu as always.

**Comment by spolu** [comment]
Hi!  This belongs to `mod_strip`. As this is the module that is in charge of populating the context menu for now.

**Comment by JamoBox** [comment]
I know the core is designed to be as minimal as possible, but surely basic context menu functionality is one of the things that _should_ belong to the core? So long as modules have ability to add their own context menu options and menus. Otherwise each module that provides a custom URL bar (anything that perfoms similar functionality to mod_strip) will surely have to reimplement context menus, which seems unexpected and out of place.
Maybe I got the wrong idea from your post, but is this something that is being worked on?

**Comment by spolu** [comment]
Or a specific module can take care of basic expected context menu so that other module don't even have to do it. We can create a module just for that, but it does not "need" o be in core right? So it does not really belong there :)

**Comment by JamoBox** [comment]
Well the reason I say the core seems fitting for the minimal context menu is because there are right-click operations that are consistent throughout pretty much all browsers; those being back, forward, refresh/reload along with text/image options, so it seems out of place for them to belong in another module where variations would have to reimplement it. I can see where you are coming from though, but this idea is literally to prevent the likes the original bug being common once the project becomes popular with lots of varying modules offering similar functionality. (Once you create a module for anything, it should be anticipated that a handful more alternatives pop up).  

Whilst being completely modular is a nice foundation, a stable, reliable core should not be compromised. I doubt users will want to be running around installing modules for basic browser functionality.

**Comment by spolu** [comment]
This could be solved by module dependencies as an example.

**Comment by spolu** [comment]
This is still totaly WIP of course
