### ISSUE TITLE
"Error: Running without the SUID sandbox!" on Linux

### ISSUE THREAD

**Issue by ColemanGariety** [spolu/breach_core#119]
I'm running the latest Arch Linux build, and when running breach I get the following:

```
browser_main_loop.cc (172): Running without the SUID sandbox!
```

I think the chrome sandbox install shell file (mentioned [here](https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment)) should be packaged with the Breach download so we can install it easily. Or provide breach in various linux distros and install it automatically when downloaded.

As for this moment it's impossible to run Breach on my system.

**Comment by spolu** [comment]
The thing is that the sandbox needs to be SUID.
You can setup everything as explained here: https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment

**Comment by willbprog127** [comment]
I have the same problem.  I really think a better error message (or even a small blurb in the README about how to fix this) would be better than some cryptic message.  Breach looks cool, but is useless to me if I can't even get it running without reading some long page on Google.

**Comment by ColemanGariety** [comment]
@spolu I tried to set it up for a few hours, it seems like the steps are:
1. Install the depot tools
2. Clone chrome source and chrome_sandbox source
3. Compile chrome_sandbox
4. Run the .sh file

I ran into a wall with step 2 when the depot tools threw a syntax error with the python `fetch` file. I started to downgrade my python to see if it was version related, but decided to post here to find a better way.

Does using Breach on Linux require setting up the chrome/sandbox dev environment and running a shell script?

**Comment by ColemanGariety** [comment]
@willbprog127 how did you fix it? When did you do to get ahold of the shell file the page refers to?

**Comment by willbprog127** [comment]
@JacksonGariety I did not fix it.  Waiting for this project to mature a bit before trying again.  Just got stung by a bunch of bees, so I'm grouchy...sorry

**Comment by ColemanGariety** [comment]
@spolu Your help would be much appreciated here. I'm using IceWeasel at the moment and it doesn't have OpenGL. This is how heart attacks happen I think.

**Comment by VxMxPx** [comment]
Here's the solution if you wanna try it:

https://github.com/breach/breach_core/issues/60#issuecomment-48656278

**Comment by ColemanGariety** [comment]
#60 works, and it's open, so I'm closing this as dupe.
