### ISSUE TITLE
[gh-pages] display errors

### ISSUE THREAD

**Issue by ghost** [spolu/breach_core#123]
The standard site http://breach.cc is looking normal. But If I go to https://breach.github.io/breach_core it doesn't looks very well (attached picture)
Is this a bug? Or is the gh-pages site not under active development?

~smens
![pages](https://cloud.githubusercontent.com/assets/8080466/3564244/2bbf09c6-0a78-11e4-8b3a-4440b4e3c54e.PNG)

**Comment by ishantheperson** [comment]
I think this could be a Jekyll error. The entire assets folder seems to not have been copied

**Comment by brayniverse** [comment]
It's because all the asset references are prefixed with a slash which will force them to load from the document location hostname.

**Comment by spolu** [comment]
Can you generate a PR?

**Comment by spolu** [comment]
Thanks!
