### ISSUE TITLE
Native tabs/documents

### ISSUE THREAD

**Issue by aral** [spolu/breach_core#124]
First off, love what you’re doing with Breach. Just been playing/hacking with it for a few minutes and it’s awesome.

One issue I ran into immediately, however: Since the tabs/documents are not native, it is (correct me if I’m wrong) impossible to match functionality in other browsers of snapping off tabs or moving tabs between different windows. I was wondering if it would make sense to expose the document/window/tab model natively to allow for this.

Regardless, excellent work and I look forward to playing with it further :)

**Comment by spolu** [comment]
The whole point is to avoid native code ;-)
As far as supporting that, we could do it across windows using html5 drag and drop.

**Comment by aral** [comment]
Indeed — I appreciate that ;)

I just wonder where the line should be between native functionality and web extensions. If a browser built on Breach cannot compete with native browsers on usability of tabs and primary chrome, the rest of the functionality may not be enough to convince people to switch.

e.g., Use case: I am used to grabbing a tab and dragging it and — boom — I have a new window. I can’t see how we would do this with HTML alone. And that’s a basic piece of functionality.

I guess what I’m saying is that you’re currently drawing the line at the window chrome and I feel the line should be drawn at multi-document/window handling :)

**Comment by spolu** [comment]
This is just mod_strip as it is implemented right now that does not support multi-windows. But there is definitely built-in support for multi-windows in `breach_core`

Now avoiding native code can create some limitations... as the one you decsribe here. But there are not that many of them fortunately!

**Comment by miketheprogrammer** [comment]
@aral, while dragging off the window may not be possible, you have to think creatively.
Right click menu of tab can have two options
--break tab
--migrate tab
Break tab creates a new Breach process, pointing to a new gig.fs register with the new tab pre inputted.
Migrate Tab, can use scuttlebutt or substacks seaport or airport to create a peer to peer, or registry based storage of available breach processes, you can get migrate the tab to one, it will then use the same gig.fs manipulation strategy to add the tab.
The breach process can have a watch on gig.fs for when it changes and cause a tab to open.

**Comment by aral** [comment]
Hi Michael,

Or, here's an idea: we could think even more creatively and add a context menu item to open up a Terminal window and the user can type in:

window xCoor yCoor width height <tintInHSLA> [<tabIndex1>, <tabIndex2>, …]

Aral

**Comment by spolu** [comment]
Closing as this belongs to mod_strip or a new module that would support multiple windows
