### ISSUE TITLE
Support chrome/chromium-flags

### ISSUE THREAD

**Issue by mrohnstock** [spolu/breach_core#135]
I like this project, it would fit my needs better, than node-webkit do, only some chrome/chromium-flags are missing
- `--kiosk`, differs from [html5-fullscreen](https://github.com/breach/exo_browser/issues/153), in the way, that the user can't leave fullscreen mode
- `--disable-web-security`, would help webapp-developers develope their apps, without messing with permissions

**Comment by spolu** [comment]
Thanks. very good points. `--kiosk` is a chrome flag? not node-webkit?

**Comment by mrohnstock** [comment]
No, it's also supported in chrome/chromium (http://peter.sh/experiments/chromium-command-line-switches/#kiosk) :)

**Comment by mrohnstock** [comment]
It would also be cool to start breach with a url, like this would work with chrome `/usr/bin/google-chrome https://github.com/breach/breach_core/issues/135`, which will open chrome with the url opened.

**Comment by spolu** [comment]
Yep totally

**Comment by t-lutz** [comment]
For what it's worth, adding the kiosk mode for the GTK based browser is quite simple. The patch below should do it.
I just started going through the code, there might be cleaner ways to do this, but I can PR this if anyone is interested.

```
diff --git a/src/browser/exo_browser_gtk.cc b/src/browser/exo_browser_gtk.cc
index b902e54..cf16abf 100644
--- a/src/browser/exo_browser_gtk.cc
+++ b/src/browser/exo_browser_gtk.cc
@@ -8,11 +8,13 @@
 #include <gtk/gtk.h>
 #include "base/file_util.h"
 #include "base/threading/thread_restrictions.h"
+#include "base/command_line.h"
 #include "ui/gfx/image/image.h"
 #include "ui/gfx/image/image_skia_rep.h"
 #include "ui/gfx/codec/png_codec.h"
 #include "content/public/browser/web_contents.h"
 #include "content/public/browser/web_contents_view.h"
+#include "exo_browser/src/common/switches.h"
 #include "exo_browser/src/browser/exo_frame.h"

 using namespace content;
@@ -107,6 +109,10 @@ ExoBrowser::PlatformCreateWindow(

   // Finally, show the window.
   gtk_widget_show_all(GTK_WIDGET(window_));
+
+  // handle kiosk mode
+  if(CommandLine::ForCurrentProcess()->HasSwitch(switches::kExoBrowserKiosk))
+    gtk_window_fullscreen(window_);
 }


diff --git a/src/common/switches.cc b/src/common/switches.cc
index 6e70aab..7c8abc1 100644
--- a/src/common/switches.cc
+++ b/src/common/switches.cc
@@ -10,5 +10,7 @@ namespace switches {
 const char kExoBrowserDataPath[] = "data-path";
 // Prevents the launch of the default 'app/' and runs the in "raw" mode
 const char kExoBrowserRaw[] = "raw";
+// Launches ExoBrowser in fullscreen mode
+const char kExoBrowserKiosk[] = "kiosk";

 }  // namespace switches
diff --git a/src/common/switches.h b/src/common/switches.h
index 50ea242..cb5128c 100644
--- a/src/common/switches.h
+++ b/src/common/switches.h
@@ -11,6 +11,7 @@ namespace switches {

 extern const char kExoBrowserDataPath[];
 extern const char kExoBrowserRaw[];
+extern const char kExoBrowserKiosk[];

 }  // namespace switches
```

**Comment by spolu** [comment]
Feel free to make a PR on exo_browser! We'll probably want OSX support as well, though :)
You can have a look at how atom-shell and node-webkit do it...

In the next release of ExoBrowser we'll probably get rid of GTK for Aura but it can be definitely useful in the meantime.
