### ISSUE TITLE
Support for getUserMedia()-API is missing

### ISSUE THREAD

**Issue by mrohnstock** [spolu/breach_core#136]
`getUserMedia()` isn't working in breach.

Examples are here: http://www.html5rocks.com/en/tutorials/getusermedia/intro/
Maybe this is only a permission issue, because chrome/chromium asks for permission to use microphone/webcam?

**Comment by spolu** [comment]
Yep we need to add APIs in the ExoBrowser to ask permission to the user so that that permission is displayed in the UI...

**Comment by spolu** [comment]
See https://github.com/breach/exo_browser/issues/106

**Comment by mrohnstock** [comment]
Asking for permission could get bypassed with `--disable-web-security`-flag in chrome/chromium by the way (#135).

**Comment by spolu** [comment]
tagged as enhancement
