### ISSUE TITLE
Getting started on readme

### ISSUE THREAD

**Issue by giovaneliberato** [spolu/breach_core#139]
How about some instructions about how to start to contribute, code patterns, how to run local, how to run tests, etc?

**Comment by spolu** [comment]
Yes! breach.cc.hack + the wiki here are early part of it. Any subject you'd like covered in particular?

**Comment by giovaneliberato** [comment]
I'm kinda newbie with node.js so I'd like to see a step by step tutorial about how to contribute, mainly how to run locally

**Comment by knownasilya** [comment]
@giovaneliberato See here: https://github.com/breach/breach_core/wiki/Building-Breach-from-Source

**Comment by knownasilya** [comment]
@giovaneliberato maybe you can get familiar and write up a small PR to add a **Contributing** section to the readme, with a link to that wiki page.

**Comment by spolu** [comment]
We probably want to create a Contriuting Wiki page entirely with how to contribute to `breach_core` + the distinction between contributing to breach_core and bulding modules.

**Comment by giovaneliberato** [comment]
@knownasilya great! i'll try to write something after get familiar.

i'm used with web development, so i'll need some time to know how to develop a desktop application.. Basically you write changes in the code and run the breach again, right?

**Comment by spolu** [comment]
@giovaneliberato if you're contributing to a module you can just restart the module from Breach or reload just the UI

**Comment by giovaneliberato** [comment]
great, thats why I love dynamic languages!! :p

**Comment by miketheprogrammer** [comment]
@giovaneliberato Please hop in IRC. Theres a few of us in there a fair amount of the time, that have built from source and are contributing actively. We can help.
1. (me) mhernandez1
2. ZeusInTraining

I believe a few others. As well knownasilya is in there also and spolu.
