### ISSUE TITLE
Do you support right click (Save Image etc.) ?

### ISSUE THREAD

**Issue by alexohneander** [spolu/breach_core#145]

**Comment by spolu** [comment]
Not full support for now (only reload, next, prev, inspect)
But we need to move all the context menu handling in a specific module and extend as much as we can the support for context menu functionalities including (save image etc...)

We will probably soon split `mod_strip` in `mod_strip`/`mod_inspect`/`mod_context` and we can work from there to add support for a richer context menu!

**Comment by knownasilya** [comment]
:+1: That is good to hear.

**Comment by spolu** [comment]
Closing as this belongs to `mod_strip` or an eventual `mod_context`
