### ISSUE TITLE
Full screen on mac with second monitor has dark bar at top of screen

### ISSUE THREAD

**Issue by hughrawlinson** [spolu/breach_core#146]
Ok, github is not working well with dropbox hosted images, here's a link: https://www.dropbox.com/s/tbrjkls2aut2ujp/Screenshot%202014-07-15%2019.04.23.png

This is what happens when I full screen breach on mac mavericks. (for those of you who don't do images, the space where the taskbar would be is replaced by 'dark'). I'd imagine this is caused by hiding the taskbar but not moving the window up? I dunno, I'm not a Mac dev, but I'm hoping my hypothesizing would help. It works fine when I don't have the second monitor plugged in.

**Comment by spolu** [comment]
Weird. does not reproduce here on 10.9. We hook into Cocoa APIs fairly standardly here for fullscreen mode.

**Comment by spolu** [comment]
Ah! You have two monitors. Damn. Interesting. Can you file an issue on http://github.com/breach/exo_browser ?

**Comment by hughrawlinson** [comment]
Sure

**Comment by alexohneander** [comment]
Hmm, does not reproduce here on 10.9.4!

**Comment by hughrawlinson** [comment]
You've tested with a second monitor? Maybe it's related to my monitor setup, I have a really lo-res second monitor. Or, it could be related to the fact that one monitor is the built in retina monitor in my MBP with a drastically better DPI than the external one.
