### ISSUE TITLE
Where to start?

### ISSUE THREAD

**Issue by udayms** [spolu/breach_core#147]
Once installed, I am not able to do anything with the browser. I am not getting an address bar or tab strip.

![screen shot 2014-07-16 at 2 27 03 am](https://cloud.githubusercontent.com/assets/186861/3596904/a0fa53e4-0ccb-11e4-8fc9-09fb20e4174c.png)

Am I missing some step here?

**Comment by tmn** [comment]
You need to install mod_strip to get the address bar and tabs.

**Comment by brayniverse** [comment]
I had a bit of trouble installing `mod_strip`. If this is still an issue for you then try clicking 'Replay onboarding' which will take you through the intro and install `mod_strip` for you.

**Comment by spolu** [comment]
This is surprising. Yes you can replay the onboarding or install the module directly with `github:breach/mod_strip` in the install bar.
