### ISSUE TITLE
Make API methods consistent

### ISSUE THREAD

**Issue by brayniverse** [spolu/breach_core#152]
Hey @spolu I have noticed that in the **modules** module you have a method called `modules_list` whereas in the ••tabs•• module you make the list available through `tabs_get` without any arguments.

What I am proposing is that we remove the list functionality from the `tabs_get` method and put it into it's own `tabs_list` method.

I can make a PR with this change but I want to check whether you had any other plans first.

**Comment by brayniverse** [comment]
`tabs_list` could just be an alias for `tabs_get` without any arguments if it will conflict with anything.

**Comment by spolu** [comment]
I guess we can close this one then
