### ISSUE TITLE
'Open in New Tab' Context Menu Option

### ISSUE THREAD

**Issue by tylerFowler** [spolu/breach_core#165]
It woud be handy to add 'Open in New Tab' when context menu is opened on a link. I'd be interested in implementing this, but it looks like click events (i.e., registering a click event and knowing that what was click on was a link) occur in exo_browser rather than breach_core? I could be wrong about that though.

**Comment by MaximOrlovsky** [comment]
vote for this issue

**Comment by t-lutz** [comment]
status -> accepted
assigned -> t-lutz

**Comment by t-lutz** [comment]
This [branch](https://github.com/t-lutz/breach_core/commit/14da52dfc1bff1c1be9147838278ebfa24d9f98d) does 80% of the job. 

It does everything except... creating the new tab. I'm not quite sure why. If someone wants to have a look at it. I'll PR once it is working.

**Comment by brayniverse** [comment]
This is the same issue I'm having with #106. As far as I am aware the actual visual tab element is created with `mod_strip` but I still can't figure out how to get that module to update after the new tab is created.

**Comment by brayniverse** [comment]
I would have assumed that [this line](https://github.com/breach/breach_core/blob/master/lib/core_tabs.js#L451) would broadcast the message and `mod_strip` would be listening so that it can update the interface.

**Comment by t-lutz** [comment]
I tried this, among other things, but the new tab is still not shown.
The logs show that a new frame is created in exo. 

The only difference in the logs between opening a new tab using the mouse middle button and opening one programatically is the call to `OpenURLFromTab` in exo.

**Comment by t-lutz** [comment]
solved, you need to emit `tabs:created` in the cb. See my PR in 2 mins.

**Comment by t-lutz** [comment]
status -> code review & validation
assigned -> @spolu

**Comment by spolu** [comment]
Thanks for the awesome work @t-lutz !

**Comment by t-lutz** [comment]
status -> closing
reason: migrated to breach/mod_strip#57
addigned -> @spolu
