### ISSUE TITLE
How to clear cache / cookies ?

### ISSUE THREAD

**Issue by antoniobrandao** [spolu/breach_core#181]
I'm stuck on a bad login, can't go back without clearing cache / cookies but I can't find such option or module....

**Comment by t-lutz** [comment]
I think you need to nuke the entire session for now. Delete `~/Library/Application Support/breach` on OSX, or `~/.breach` on Linux. This will also delete modules and so on, and start a fresh browser.

**Comment by t-lutz** [comment]
You can probably just delete the module folder in this directory (or the local copy) if you know which module is causing the issue.

**Comment by antoniobrandao** [comment]
Cool, thanks. I also tried to just delete the contents of the folder "sessions" therein, but to no avail. Your solution worked, but it's a long stretch just to delete the cache.

Looking forward for a clear-cache module ! :)
