### ISSUE TITLE
OSX Yosemite Capatability

### ISSUE THREAD

**Issue by matthewjamesr** [spolu/breach_core#182]
Hello gents,

Just curious as I am wanting I install the new OSX beta, has anyone been successfully wen using breach on it? Thanks!

**Comment by brayniverse** [comment]
I've used it on both Mavericks and Yosemite and they work the same.

**Comment by charleshaa** [comment]
I have it on Yosemite and as of now I only managed to display Google properly. Pretty much any other site I tested breaks as soon as I scroll...

**Comment by yperson** [comment]
On Yosemite, as soon as you wanna scroll, the whole page becomes white.

**Comment by brayniverse** [comment]
Does anybody know why this is happening?

**Comment by spolu** [comment]
I would need to investigate this on a OSX 10.10 machine. My intuition tells me this is related to exo_browser's use of WebContents HasShown method... But this is a long shot

**Comment by brayniverse** [comment]
Bummer, I was hoping it was something I could help fix. Sorry but I don't have enough experience with C++ to help.

**Comment by spolu** [comment]
Closing as duplicate of #116
