### ISSUE TITLE
Key events aren't occuring

### ISSUE THREAD

**Issue by kyleshrader** [spolu/breach_core#186]
I was having trouble with mod_strip reacting to keyboard shortcuts, so I created a quick module to hook onto tabs:keyboard and controls:keyboard. I was still not receiving any events. Is anyone else experiencing this?

**Comment by spolu** [comment]
Hi! Did you make sure to call `register` on the proper event types before listening on them?

See mod_strip's `index.js`

**Comment by spolu** [comment]
All these keys are supposed to work. You're the second person reporting that issue... this is very interesting. I'm curious to discover where the keys don't get propagated. 

Marked as bug

**Comment by kyleshrader** [comment]
I'll check when I'm home; however, even at work I'm seeing mod_strip not work.. im on ubuntu (sorry for deleting comment heh)

**Comment by spolu** [comment]
OK! Thanks! Here on ubuntu works great.

**Comment by kyleshrader** [comment]
I uncommented the logging for mod_strip and it is logging. So it isn't related to breach_core I guess... This can be closed and I'll investigate further, using the ticket in mod_strip.

**Comment by spolu** [comment]
Awesome. That's good news :)
