### ISSUE TITLE
Calling tabs_close will not actually close the tab

### ISSUE THREAD

**Issue by nearsyh** [spolu/breach_core#189]
After calling the tabs_close, the page will be blank, but the tab won't disappear.

I think the reason is that to actually delete the tab displayed by mod_strip, we need to do this in [Line361](https://github.com/breach/mod_strip/blob/master/lib/tabs.js#L361). However calling tabs_close which is in the breach_core module won't do this. Adding a tabs:close event may be good?

**Comment by spolu** [comment]
There `my.core_tabs` is local to `mod_strip` and has nothing to do with any object in `breach_core`... right?

**Comment by nearsyh** [comment]
Exactly. But the problem is when I call tabs_close in other modules, the corresponding tab displayed by mod_strip is not closed (only become blank).

**Comment by spolu** [comment]
Yep... We should probably add some code in mod_strip to handle that case. Would you feel like making a PR on `mod_strip`?

**Comment by nearsyh** [comment]
Sure

**Comment by spolu** [comment]
Awesome! :)
