### ISSUE TITLE
Search using accented/special characters are transformed into "?"

### ISSUE THREAD

**Issue by nandobang** [spolu/breach_core#199]
Whenever I do a search using the search bar, characters like "ã" or "ç" are transformed into "?" before being sent to Google.

My Breach version is v0.3.22-alpha.6 and mod_strip is v0.2.12.

**Comment by spolu** [comment]
Hi I think this is a duplicate of this: https://github.com/breach/mod_strip/issues/46

This definitely belongs to mod_strip.

Thanks!
