### ISSUE TITLE
Not openning, mac

### ISSUE THREAD

**Issue by ghost** [spolu/breach_core#201]
### I recently downloaded breach from breach.cc for mac os x 10.6.0 and it is not openning.

or atleast taking a long time to open

**Comment by pdelanauze** [comment]
`rm -rf ~/Library/Application Support/breach`

**Comment by ghost** [comment]
Thank you

**Comment by ghost** [comment]
Still does nothing

On Thu, Aug 21, 2014 at 4:54 AM, Patrick de Lanauze <
notifications@github.com> wrote:

> rm -rf ~/Library/Application Support/breach
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/breach/breach_core/issues/201#issuecomment-52875786.

## 

_Zyluss_
_Website Developer_

_@Zyluss_ http://twitter.com/Zyluss__
_Website_ http://zyluss.github.io

**Comment by miketheprogrammer** [comment]
How are you trying to open it. Try removing any Libraries with breach.
Also this ticket may be affecting you.
https://code.google.com/p/chromium/issues/detail?id=380199

Lastly, when @spolu gets back he may be able to help you.

**Comment by jacopocolo** [comment]
Same problem here, Breach shows up in the dock but does not start. I tried removing breach folder from the Library but nothing changed. I'm running OSX 10.6.8

**Comment by miketheprogrammer** [comment]
@jacopocolo I am hoping finishing work on ExoBrowser 0.7 will help. With a simplified build process and less technologies in the stack, maybe we will be able to fix most startup issues.

**Comment by ghost** [comment]
This is a shame I had high hopes for breach and it won't even start lol

**Comment by matthieubessol** [comment]
I've got nearly the same problem. I've downloaded once and it worked perfectly. I deleted it (still don' know why) and then downloaded again. Now, I can't open it. The windows appears just for a second and close. I'm running Yosemite.

**Comment by miketheprogrammer** [comment]
Please everyone. Remember that current release of breach is an Alpha
version. The whole underlying technology stack has been reworked and breach
will see some huge changes very soon. All of these ideas are bleeding edge
of custom browser technology, with it comes mistakes and learning
experiences.

**Comment by KyleGoddard** [comment]
From the OS X console. (Yosemite)

2015-01-27 9:18:35.811 AM Breach[1516]: Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
2015-01-27 9:18:35.908 AM ExoBrowser Helper[1518]: Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
2015-01-27 9:18:36.718 AM ExoBrowser Helper[1519]: Internals of CFAllocator not known; out-of-memory failures via CFAllocator will not result in termination. http://crbug.com/45650
2015-01-27 9:18:36.969 AM com.apple.xpc.launchd[1]: (org.breach.Breach.321804[1516]) Service exited with abnormal code: 1

**Comment by ghost** [comment]
I've sorted this out. No probs
