### ISSUE TITLE
Unable to browse with touchpad scrolling 

### ISSUE THREAD

**Issue by reanimus** [spolu/breach_core#202]
Any page that requires scrolling down is unusable in breach (using OS X 10.10 DP5, but iirc this occurred on my work laptop running 10.9.4 as well). For example, the breach homepage:

![Breach before attempting to scroll](https://cloud.githubusercontent.com/assets/1053912/3945828/177bc714-2653-11e4-837e-a857b5e6285f.png)

Then when I try to scroll:

![Breach after attempting to scroll](https://cloud.githubusercontent.com/assets/1053912/3945824/f9aa82c0-2652-11e4-9fa7-d1cfb1256b28.png)

This occurs whether i try two-finger scrolling or use the arrow keys/page-down to scroll.

**Comment by brayniverse** [comment]
This is a known issue that only seems to occur on Macs.

**Comment by reanimus** [comment]
Is there any known workaround?

**Comment by brayniverse** [comment]
Not that I'm aware of.

**Comment by spolu** [comment]
This is a known issue on Yosemite. It should get fixed in the next version.

**Comment by spolu** [comment]
Please track progress here:https://github.com/breach/exo_browser/issues/145
