### ISSUE TITLE
Is there any way to have multiple instances that are built on different modules? In another word, profile mechanism

### ISSUE THREAD

**Issue by ken-okabe** [spolu/breach_core#211]
Truly great concept and implmentation. Exciting and thanks.

The author mentioned the concept of `breach` as a modular browser is different from `node-webkit` and I strongly support the concept and approach, however, I am pretty sure this project has a great possibility to become the alternative. In fact, I am the one who seeked the alternative of `node-webkit` since it fails to work on Ubuntu14.04, and probably many others want `breach` as an app framework.

Surely, even now, an app developer can develop any modules and inculde them to `breach`, but as an developer who has some experience to develop such a thing with Chrome or Firefox, in many cases, it's definitely better to separate instances and make them isolate mostly for the stability.

Furthermore, come to think of it, even sticking to the conception as browser framework, let's investigate the legacy browser world. Chrome or Firefox are already implemented with a poplular useful feature - `profile` that allows to have multiple isolated browser instances with another set of extensions. `breach` also will have `profile` mechanism in future, I am sure. In such a scenario, after all, which simply means `breach` can be any apps on each profiles with the isolation. 

So here's my question. Is there any way to have multiple instances that are built on different modules? So far, I tried to have multiple instances of the projects in different directories for each, but they seem to sync, probably for Chrome sandbox is identical.

Thanks for your thought on this.

**Comment by spolu** [comment]
You want to use http://github.com/breach/thrust

This is not yet ready for showtime but you can follow that issue for updates: https://github.com/breach/thrust/issues/161

**Comment by ken-okabe** [comment]
spolu, thanks for letting me know, I will install and study from now.

I also appreciate if you post some article for layer relation and development cycle of exo-browser, thrust(exo-shell) and breach. There might occur some confustion among developers, so.

Thanks!

**Comment by spolu** [comment]
Yes. You're totally right, and such a blogpost is definitely planned!
