### ISSUE TITLE
I can't download Breach on Windows.

### ISSUE THREAD

**Issue by dasalvar** [spolu/breach_core#214]
I'm having problems downloading Breach. The download button on the website doesn't work, I've tried with Chrome and IE11 and nothing triggers.

Is there an alternative way to download and install Breach?

**Comment by spolu** [comment]
Hi @dasalvar! Unfortunately, Breach is not suopported on windows, but you can track that issue here: 
https://github.com/breach/breach_core/issues/90

We're working hard on https://github.com/breach/thrust which will bring support on Windows to Breach.
