### ISSUE TITLE
Did you forget the windows build??

### ISSUE THREAD

**Issue by ericrange** [spolu/breach_core#217]
Did you forget the windows build?? the issue for the windows build is months ago...

**Comment by jelenaljaz** [comment]
Can't you people just wait without constant nagging? It'll be ready when it's ready. I promise you, your (and others') constant demands for the Windows build won't speed up the process.

**Comment by ericrange** [comment]
sure it wont?? :D :P

**Comment by Faleij** [comment]
I at least am sure as hell it won't.
Please don't open issues that clearly are duplicates, especially when you already have spammed "+1" in the original issue, and please stop with the "+1" on github, it generates unnecessary email spam to those whom subscribe to a repo.

**Comment by morganrallen** [comment]
This repo is rather dated anyhow. Please refer to https://github.com/breach/thrust

**Comment by ericrange** [comment]
the hugh amount of "+1" represents the NEEEDD of a windows build :D

**Comment by morganrallen** [comment]
And FWIW +1ing is more annoying than productive, we know people want a Window build, it is currently available, and had you read the previous thread you +1d you would have seen this is obsolete now.

https://github.com/breach/breach_core/issues/90#issuecomment-62414317

**Comment by spolu** [comment]
That's fine to ask guys!

We needed to build Thrust https://github.com/breach/thrust before getting Breach to the next version. Good news is that Thrust targets Windows, and we'll start soon working on the next version of Breach.

I'll update the windows issue as soon as I have something runable on windows! Promises! :+1:

**Comment by ericrange** [comment]
that is a good answer :)

**Comment by spolu** [comment]
We're here for that! :)
