### ISSUE TITLE
No Windows version?

### ISSUE THREAD

**Issue by socheatsok78** [spolu/breach_core#220]
@@ nothing to say

**Comment by sebastien-bartoli** [comment]
See here : https://github.com/breach/breach_core/issues/90

**Comment by atomic1fire** [comment]
I've been playing with Jankybrowser, so I can confirm that windows support works pretty okay.

I probably butchered the jankybrowser UI in the interest of science. But I can confirm jankybrowser is really easy to theme if you already know css and html.

![image](https://cloud.githubusercontent.com/assets/613800/5508027/33480012-876e-11e4-861a-5a62b4b69664.png)

**Comment by morganrallen** [comment]
Nice! That looks slightly less horrible.
