### ISSUE TITLE
Changing default search engine?

### ISSUE THREAD

**Issue by Pitu** [spolu/breach_core#226]
Is it possible to override the search engine currently used with one of our own choosing?

**Comment by Seonnyn** [comment]
It is.
You can clone yourself the mod_strip and change the lib/box.js file on line ~224 and change the submit_url to an engine you want to use. P.e. for duckduckgo it would look like this afterwards:

From:

``` javascript
else {
submit_url = 'https://www.google.com/?' +
                     'q=' + escape(data.input) + '&' +
                     'ie=UTF-8';
}
```

To:

``` javascript
else {
submit_url = 'https://www.duckduckgo.com/?' +
                     'q=' + escape(data.input) + '&' +
                     'ie=UTF-8';
}
```

Then use your local mod_strip and when you then type something in the searchbox, it will be using your favorite search engine.

**Comment by Pitu** [comment]
I was digging through the source files before asking but didn't find where this was as I still don't know the folder structure and how it works. Thank you @Seonnyn !
