### ISSUE TITLE
Someone bring back this project!

### ISSUE THREAD

**Issue by CosmicWebServices** [spolu/breach_core#233]
I used and I wanted to see if there was a update and it was down.

**Comment by alexohneander** [comment]
i would programm alot of tools, when somebody could help me to understand the api.

**Comment by elkwood** [comment]
I switched to https://github.com/atom/electron

**Comment by morganrallen** [comment]
Just coming to comment on this. Yes, give electron a try. This project was basically abandon when when Atom/Electron added the functionality (a bare shell) this project was trying to supply. Not sure what if there is any plan moving forward.

**Comment by JoshTheDerf** [comment]
If anyone wants a basic web browser, based on electron, that's incredibly hackable (pretty much everything is an "extension"), you could take a look at https://github.com/Tribex/iBrows. I'd probably rewrite it before doing anything serious with it though.

**Comment by CosmicWebServices** [comment]
ibrows looks cool

**Comment by CosmicWebServices** [comment]
How can electron be better isn't it a text editor?

**Comment by JoshTheDerf** [comment]
@CosmicWebServices No, it's a [runtime](http://electron.atom.io/) on which a text (and more) editor ([Atom](http://atom.io/)) is built. Quite enjoyable to use I might add.

**Comment by CosmicWebServices** [comment]
Sorry I noticed that after I commented
