### ISSUE TITLE
Cannot load certain web pages

### ISSUE THREAD

**Issue by JeanLafleur** [spolu/breach_core#24]
www.streamnation.com/login
On this page, I should see the fields to login via email or Facebook.
But I cannot see any of the fields

**Comment by spolu** [comment]
You're running v0.1.4 right?

**Comment by JeanLafleur** [comment]
I wasn't. It works on v0.1.4
We should display the entire version number in the default page when you open a tab.
Right now it is only written v0.1.
I saw the issue with the auto-update which would solve the issue actually

**Comment by spolu** [comment]
Yes auto-update is a long story... :)
