### ISSUE TITLE
Use signature instead of hashing for auto-update

### ISSUE THREAD

**Issue by spolu** [spolu/breach_core#32]
When running auto-updates, packaged updates should be signed and the signature verified instead of realying on simple hashing (esp. md5)

**Comment by spolu** [comment]
@deian all yours!

**Comment by spolu** [comment]
Ideally the signature should be computed in `dist/darwin.js` and `dist/linux.js` to easily update the auto-update server.

**Comment by deian** [comment]
I need to tweak this a bit more, but I'd be curious to get your thoughts on the approach.

E.g., do we want a single signature file containing all the sha1sums?

**Comment by spolu** [comment]
We can upload the signature file next to the tarball on s3 and point to it in the json from `update.url`, no?

**Comment by spolu** [comment]
Thanks @deian for the implementation!
