### ISSUE TITLE
App logo enhancements

### ISSUE THREAD

**Issue by spolu** [spolu/breach_core#43]
from @guille:

> - download: slow, why not just the updater?
> - install: quicklook of icon blends with background (https://cloudup.com/cYV9ZIA9EaQ)
> - launch: went from white to dark gray (would be nice to have eventual BG color)
> - launch: seemed slow
> - usage: keyboard shortcuts missing

**Comment by spolu** [comment]
@alevizio see above as you wanted to work on the app/dock icon
@guille can you develop on the keyboard shortcuts missing?

**Comment by alevizio** [comment]
Cool @guille as I told @spolu it be awesome to work a little bit more on the icon for the launch :)

**Comment by spolu** [comment]
Most of what can be solved has been resolved in the latest version.
- Most of the flickering has been removed through tabs reuse
- But, impossible to have a screen background color right at initialization (content API internal behaviour)

@alevizio did you get a chance to have a look at the dock icon?

**Comment by spolu** [comment]
assigning to @alevizio for the app logo! :+1:

**Comment by alevizio** [comment]
@alevizio give me this weekend and I´ll get it done before launch ;)

**Comment by spolu** [comment]
That's perfect! Thanks!

**Comment by alevizio** [comment]
Hey Guys, I've testing out a couple of options, not final at all. Buy I would like to work more on one of the options. The one I'd like the best is the one in the screenshot, what do you think @spolu ?

![breach_logo](https://cloud.githubusercontent.com/assets/3001854/3505317/6eaedc82-065b-11e4-9680-43ce2247ae29.png)
![screenshot 2014-07-08 01 49 52](https://cloud.githubusercontent.com/assets/3001854/3505321/78cd22aa-065b-11e4-8205-42c0baf6d64b.png)

**Comment by spolu** [comment]
I like it as well. The idea would be to use it everywhere right?

I was wondering if it would be cool to have the "visual elements" of that one with the "perspective" of the former logo?

**Comment by alevizio** [comment]
Yep, we could use only for the icon or everywhere if you like it!

You're right, I'm going to give it a try in "perspective" to see how it looks like :+1: and work in some details.

**Comment by spolu** [comment]
Awesome!

**Comment by alevizio** [comment]
After trying lot's of stuff, I thought this was the best option for now. Maybe later on, I can try a couple of other things I missed out and take me more time.

What do you think @spolu ?

![icon3](https://cloud.githubusercontent.com/assets/3001854/3533742/b4e784d2-07d8-11e4-82b7-65127975bd95.png)
![screenshot 2014-07-09 23 19 01](https://cloud.githubusercontent.com/assets/3001854/3533745/bc8e23f8-07d8-11e4-9f8d-77eb222feee4.png)
