### ISSUE TITLE
Browser Image in Landing Page

### ISSUE THREAD

**Issue by alevizio** [spolu/breach_core#56]
Hey @spolu , here's the image for the landing we discussed that needed some change.

![browser](https://cloud.githubusercontent.com/assets/3001854/3533835/8947ea62-07db-11e4-8a05-a5f6a45574d9.png)

**Comment by spolu** [comment]
Sweet! Less urgent but well need to update the skewed one layer-01 as well no?

**Comment by spolu** [comment]
Actually it conveys that you can switch your UI to keep both... So we're good!

**Comment by alevizio** [comment]
Awesome!

**Comment by spolu** [comment]
I'm gonna try with a real one as well
![screen shot 2014-07-10 at 07 50 01](https://cloud.githubusercontent.com/assets/15067/3540278/8d0be160-0841-11e4-9c77-e2e96414b325.png)

**Comment by alevizio** [comment]
Yep, I was thinking about that, how it would look. I think we can give it a try!

**Comment by spolu** [comment]
Ill mix the two. Smaller version here
![screen shot 2014-07-10 at 07 57 27](https://cloud.githubusercontent.com/assets/15067/3540388/9b84a62c-0842-11e4-8d11-b8fc1232a5ea.png)

**Comment by spolu** [comment]
@alevizio let me know what you thinkg: http://breach.cc

**Comment by alevizio** [comment]
I like it, the only problem I find is the division between header and content. Maybe a small grey line diving it.

![screenshot 2014-07-10 12 06 34](https://cloud.githubusercontent.com/assets/3001854/3540641/bac744ac-0844-11e4-978f-fe661c11d642.png)

**Comment by spolu** [comment]
yep! let's do it

**Comment by spolu** [comment]
what about now?

**Comment by alevizio** [comment]
Excelent!
