### ISSUE TITLE
[linux] Error loading Chromium SUID Sandbox

### ISSUE THREAD

**Issue by arkokoley** [spolu/breach_core#60]
Whenever I try running breach, i get this error: 

```
./breach                                              07/11/2014 00:42:12 IST
[4413:4413:0711/004358:3080095122:FATAL:browser_main_loop.cc(172)] Running 
without the SUID sandbox! See https://code.google.com/p/chromium
/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the 
sandbox on.
./breach: line 6:  4413 Aborted                 $SRC_DIR/__AUTO_UPDATE_BUNDLE__/exo_browser/exo_browser --raw $SRC_DIR/__AUTO_UPDATE_BUNDLE__/breach_core
```

I managed to run exobrowser without SUID sandbox using the flag: 
`--disable-setuid-sandbox`. However, I couldn't manage to do the same with breach when using exo. Any ideas regarding how to do this?

I am using Linux Mint 17 64bit.

**Comment by flecno** [comment]
same for me on archlinux64

**Comment by sergiolepore** [comment]
Same on Ubuntu 14.04

**Comment by spolu** [comment]
Damn. This has to be fixed.
In the meantime you can probably run the exobrowser directly and passing it breach_core:

```
 ./__AUTO_UPDATE_BUNDLE__/exo_browser/exo_browser --disable-setuid-sandbox --raw __AUTO_UPDATE_BUNDLE__/breach_core/
```

**Comment by flecno** [comment]
Mhm... But:

```
./__AUTO_UPDATE_BUNDLE__/exo_browser/exo_browser: bad option: --disable-setuid-sandbox
```

**Comment by spolu** [comment]
Ouch. 
Would this work?

```
 ./__AUTO_UPDATE_BUNDLE__/exo_browser/exo_browser --raw __AUTO_UPDATE_BUNDLE__/breach_core/ -- --disable-setuid-sandbox 
```

**Comment by spolu** [comment]
Otherwise you can also install the sandbox locally following the instruction there...

**Comment by flecno** [comment]
no.... this will results in the same error like normal start

**Comment by spolu** [comment]
So last thing you can do is replace the content of `exo_browser/shell/*` by `breach_core/*` and then run the exo_browser with just the arg you specified

**Comment by spolu** [comment]
The ExoBrowser go fetch the content of `shell/` by default

**Comment by arkokoley** [comment]
Copying contents of `breach_core` to `exo_browser/shell/` works with the exo_browser running with `--disable-setuid-sandbox` flag. Thanks. Breach works now.

**Comment by arkokoley** [comment]
Writing this comment from Breach right now! :D 

Woohoo!

**Comment by flecno** [comment]
@arkokoley not for me. What i'm doing wrong?

```
/breach-v0.3.20-alpha.5-linux-x64 % cd __AUTO_UPDATE_BUNDLE__/exo_browser/shell/                                                       :(
..AUTO_UPDATE_BUNDLE__/exo_browser/shell % rm -rf *
..AUTO_UPDATE_BUNDLE__/exo_browser/shell % cp -a ../../breach_core/* ./   
..AUTO_UPDATE_BUNDLE__/exo_browser/shell % cd ../../../
..loads/breach-v0.3.20-alpha.5-linux-x64 %  ./__AUTO_UPDATE_BUNDLE__/exo_browser/exo_browser --disable-setuid-sandbox --raw __AUTO_UPDATE_BUNDLE__/breach_core/
./__AUTO_UPDATE_BUNDLE__/exo_browser/exo_browser: bad option: --disable-setuid-sandbox
```

**Comment by ahamilton9** [comment]
@arkokoley Worked for me as well, Linux Mint.

**Comment by ahamilton9** [comment]
@flecno I didn't remove any files from exo_browser/shell, just overwrote/merged everything. Otherwise, your commands look fine.

**Comment by arkokoley** [comment]
@flecno Everything is fine. run it as: 

```
.loads/breach-v0.3.20-alpha.5-linux-x64 %  ./__AUTO_UPDATE_BUNDLE__/exo_browser/exo_browser --disable-setuid-sandbox 

```

**Comment by flecno** [comment]
Ahh. thank you! That command works!

**Comment by spolu** [comment]
Yay! :+1:

**Comment by timmarinin** [comment]
Same problem, last command works. (Debian amd-64)

**Comment by arkokoley** [comment]
To sum up, for other linux users who might face this error, 

To run Breach, run:

```
$ cd breach-v0.3.20-alpha.5-linux-x64
$  rm -rf __AUTO_UPDATE_BUNDLE__/exo_browser/shell/*
$ cp -a __AUTO_UPDATE_BUNDLE__/breach_core/* __AUTO_UPDATE_BUNDLE__/exo_browser/shell
$ ./__AUTO_UPDATE_BUNDLE__/exo_browser/exo_browser --disable-setuid-sandbox
```

**Comment by spolu** [comment]
We'll keep this one open until it gets fixed

**Comment by arkokoley** [comment]
:+1:

**Comment by say2joe** [comment]
The above fix did NOT work on Ubuntu 14.04. Please see the following error info:

[2014-07-11T12:25:46.099Z] [index] Breach v0.3.20-alpha.5 Starting...
[2014-07-11T12:25:48.125Z] *********************************************
[2014-07-11T12:25:48.126Z] ERROR: ENOENT, stat '/home/jjohnson/npm'
[2014-07-11T12:25:48.126Z] *********************************************
[2014-07-11T12:25:48.127Z] Error: ENOENT, stat '/home/jjohnson/npm'
[2014-07-11T12:25:48.127Z]     at Error (native)
[2014-07-11T12:25:48.127Z] ---------------------------------------------

I'm not terribly sure this product is ready for _any_ kind of release if it doesn't even run / install.

**Comment by say2joe** [comment]
I figured out the problem. It was looking for npm installed locally -- mine is installed globally. Using sudo solved my problem. (I also created a symlink from $HOME/npm to /usr/bin/npm which removes my need for sudo)

**Comment by user12312** [comment]
Am running linux mint. I followed these instructions posted in here: 
$ cd breach-v0.3.20-alpha.5-linux-x64
$  rm -rf **AUTO_UPDATE_BUNDLE**/exo_browser/shell/*
$ cp -a **AUTO_UPDATE_BUNDLE**/breach_core/\* **AUTO_UPDATE_BUNDLE**/exo_browser/shell
$ ./**AUTO_UPDATE_BUNDLE**/exo_browser/exo_browser --disable-setuid-sandbox

I get the following error, "./**AUTO_UPDATE_BUNDLE**/exo_browser/exo_browser: symbol lookup error: ./**AUTO_UPDATE_BUNDLE**/exo_browser/exo_browser: undefined symbol: g_type_class_adjust_private_offset "

does anyone one have basic fool proof instructions to getting this running? I am on Linux Mint 15 Olivia. Thanks.

**Comment by puredevotion** [comment]
same problem, @arkokoley and @say2joe comments helped.

running ubuntu 14.04 amd64, chromium installed, node/npm installed through apt-get.
Wouldn't mind a apt-source for this :)

ps. typing from within breach!

**Comment by fazo96** [comment]
The fix in @arkokoley's comment helped for me. I'm on arch linux x64

**Comment by user12312** [comment]
error message I am getting is: /home/user/Desktop/breach-v0.3.20-alpha.5-linux-x64/**AUTO_UPDATE_BUNDLE**/exo_browser/exo_browser: symbol lookup error: /home/user/Desktop/breach-v0.3.20-alpha.5-linux-x64/**AUTO_UPDATE_BUNDLE**/exo_browser/exo_browser: undefined symbol: g_type_class_adjust_private_offset

**Comment by ColemanGariety** [comment]
Is there a way to get this to work out of the box? Maybe a simple re-packaging of the Beach linux dist?

**Comment by shime** [comment]
Just confirming that this command works on arch x64:

```
./__AUTO_UPDATE_BUNDLE__/exo_browser/exo_browser --disable-setuid-sandbox 
```

**Comment by miketheprogrammer** [comment]
@JacksonGariety This is an unstable alpha. There is no "out of the box". At a minimum, that comes at beta level, but only typically guaranteed at full release version. 

As this project gains momentum and gets more contributors I am sure things will work much more fluidly.

**Comment by spolu** [comment]
Hi guys, this will require packaging breach as .deb/.npm to install the sandbox SUID. That will come along the way indeed. Especially if someone wants to work on it :)

**Comment by rkyleg** [comment]
confirming arkokoley's fix works on x64 Linux Mint 17

**Comment by spolu** [comment]
Covered by addition of README in tarball and https://github.com/breach/breach_core/wiki/Running-Breach-on-Linux

**Comment by Diel1024** [comment]
"--disable-setuid-sandbox" helped
As I see, the browser can update itself. Looks great! Now, we need AdBlock and Ghostery for it:D Let's deveplop

**Comment by shaikh-shahid** [comment]
Got ya solution folks.
http://codeforgeek.com/2014/08/download-install-breach-browser-ubuntu-14-04/

**Comment by Benderwan** [comment]
Working fine on Elementary OS using ExoBrowser 32 bits

**Comment by heyjordn** [comment]
Copying the contents of breach_core/\* to exo_browser/shell worked really well for me, posting this from Breach :D
