### ISSUE TITLE
Page hangs when scrolling down

### ISSUE THREAD

**Issue by Tarang** [spolu/breach_core#63]
On nearly all websites while scrolling down the page crashes (OS X 10.10).

**Comment by spolu** [comment]
Yep we know it's not working well on Yosemite...

**Comment by Tarang** [comment]
Just thought i'd mention it i didn't see it in the closed issues. I think it affects chrome too.

A really really exceptional piece of software btw!

**Comment by spolu** [comment]
Thanks ;-)

**Comment by spolu** [comment]
duplicate of #116
