### ISSUE TITLE
[question] Implementing keycodes

### ISSUE THREAD

**Issue by luaks** [spolu/breach_core#70]
Where is it best to implement key combinations and such.
For example switching tabs in mod_strip.
Should this be done in mod_strip, or should there rather be something handling keyevents in the breach_core, to which mod_strip then registers the combinations and handlers or maybe even a completely new module, which handles this?

I would really like to use ccampbell/mousetrap, because I think it has a really great API for this.

**Comment by spolu** [comment]
It's all in `mod_strip` for now. Look for `lib/keyboard_shortcuts.js` there!

**Comment by luaks** [comment]
I really don't know how I have missed this, thanks.

Still, what do you think about a general shortcut manager in breach_core, which would be accessed from the modules? This would also make changing shortcuts a lot easier, for users.

**Comment by spolu** [comment]
Well shortcuts are really up to the modules... Let say I want to create a browser that works only with the keyboard, I'd probably need very specific shortcuts that wouldn't fit a more traditional module such as `mod_strip`.

What we can do is create a nodeJS module required by other modules to handle keyboard shortcuts in a rather "standard way"... and require that in mod_strip in place of the `keyboard_shortcuts.js` file. What say?

**Comment by luaks** [comment]
Yes, thats kind of what I meant. I could try to implement basic functionality tomorrow, but it will probably take a bit longer, because I need to get familiar with the API.

**Comment by spolu** [comment]
Cool! You can easily repackage `keyboard_shortcuts.js` in a separate package and start from there.
