### ISSUE TITLE
Unidentified developer

### ISSUE THREAD

**Issue by inorganik** [spolu/breach_core#72]
I am unable to run Breach because its developer is unidentified:

![screen shot 2014-07-10 at 4 12 10 pm](https://cloud.githubusercontent.com/assets/109553/3546086/6d19beca-087f-11e4-8cbd-6b0ed3e4ce8c.png)

I'm not sure what is involved in making it from an "identified" developer, but maybe it would be worth the trouble? Of course I can always change my security prefs, but that exposes me to security vulnerabilities.

**Comment by alevizio** [comment]
You have to go to system preferences > Security & Privacy
![screenshot 2014-07-10 19 19 32](https://cloud.githubusercontent.com/assets/3001854/3546184/4ca04550-0880-11e4-9a22-fd7c77ddbf21.png)

**Comment by inorganik** [comment]
As I said, If I change my security prefs it could expose me to security vulnerabilities. I realize with Macs this isn't a huge issue, but to play the devil's advocate, what if some kind of malware installed itself.

**Comment by alevizio** [comment]
suit yourself!

**Comment by inorganik** [comment]
Dude, this isn't a personal jab. I'm just trying to point out an issue that might prevent a lot of people from running Breach.

**Comment by framerate** [comment]
@inorganik I agree with you, but you can manually override just the single app in Security by saying "Open Anyways" and it'll only apply to breach.

But in the medium term (post alpha) the project definitely needs to be identified on downloaded binaries.

**Comment by spolu** [comment]
Definitely planned to start signing the package very soon!

**Comment by inorganik** [comment]
@framerate that's a great short-term solution. Thanks.
