### ISSUE TITLE
Does not appear to work in Snow Leopard (10.6.8)

### ISSUE THREAD

**Issue by JasonKraft** [spolu/breach_core#74]
The Breach icon appears when trying to run it on 10.6.8, but no window opens. I'd venture to guess Breach does not support Snow Leopard 10.6.8?

**Comment by spolu** [comment]
All I can say is that it wasn't tested... since it's built on 10.9... It might not work there indeed :S

**Comment by JasonKraft** [comment]
Darn. I guess it's finally time to upgrade my operating system. _whips out the backup hard drive_

**Comment by spolu** [comment]
:boom: sorry for that :(
