### ISSUE TITLE
Can't click on a filtered tab

### ISSUE THREAD

**Issue by savetheclocktower** [spolu/breach_core#79]
Say I've got some tabs.

![screen shot 2014-07-10 at 7 23 40 pm](https://cloud.githubusercontent.com/assets/3450/3547142/df4fd3aa-0891-11e4-9dc7-68b6226ea614.png)

I type a search term to filter them…

![screen shot 2014-07-10 at 7 24 59 pm](https://cloud.githubusercontent.com/assets/3450/3547148/eb9c1d76-0891-11e4-883f-598b5a1c5520.png)

Then I try to click on the first result, but instead the currently selected tab remains focused and I'm back where I started.

![screen shot 2014-07-10 at 7 23 40 pm](https://cloud.githubusercontent.com/assets/3450/3547142/df4fd3aa-0891-11e4-9dc7-68b6226ea614.png)

**Comment by spolu** [comment]
Nice catch! definitely a bug... belongs to http://github.com/breach/mod_strip

**Comment by savetheclocktower** [comment]
Ah, of course. Shall I file it there?

**Comment by spolu** [comment]
That'd be awesome!

**Comment by spolu** [comment]
duplicate of https://github.com/breach/mod_strip/issues/21
