### ISSUE TITLE
Contains licensed fonts (Gotham Rounded)

### ISSUE THREAD

**Issue by archseer** [spolu/breach_core#80]
https://github.com/breach/breach_core/tree/master/controls/assets/fonts

You probably want to remove Gothan Rounded (and delete it from the git history), as it is a commercially available font; and I presume not freely distributable.

**Comment by spolu** [comment]
You're right. Will have to find an alternative cc @alevizio

**Comment by larryfox** [comment]
Just a heads up it's also in your [mod_strip](https://github.com/breach/mod_strip/tree/master/controls/assets/fonts) repo. Might want to make this a priority, you can be severed a DMCA takedown for this kind of thing.

**Comment by archseer** [comment]
Yes, indeed, this should be removed ASAP, then you can take your time and look for a viable replacement.

[Removing sensitive data](https://help.github.com/articles/remove-sensitive-data)

**Comment by alevizio** [comment]
@archSeer @spolu @larryfox I have the license for that font since I bought it but we should read it more carefully just in case. We could look for a google webfont that's similiar just to be safe maybe.

**Comment by alevizio** [comment]
The Varela Round is very similar, but doesn't have as much variables as gotham. Would you like me to give it a try in the landing page and see how it looks? Later on in the app

https://www.google.com/fonts/specimen/Varela+Round

**Comment by archseer** [comment]
@alevizio Yes, but the license normally works per-computer, or in the case of a web license, you must guarantee that the font is only usable for rendering on that specific website, and not downloadable (basically, they allow you to use it on your own page, but you must make sure people cannot just pirate it). I am pretty sure that storing the font files in a publicly available repository anyone can download is outside the terms of the license.

**Comment by AdrianTP** [comment]
A decent readable font that you could use as a drop-in emergency replacement is [Roboto](http://www.google.com/fonts/specimen/Roboto). It's Apache licensed. Once you have that in place, you can spend more time looking for a font you think represents Breach better.

**Comment by eiszfuchs** [comment]
I'm not an expert, but couldn't you just use the system's default font for UI elements (tabs, navigation bar, menus)? For Mac OS, that'd be _Helvetica Neue_, Ubuntu has its own font, _Ubuntu_, and recent versions Windows use _Segoe UI_ - and every system displays these fonts best and most readable (certain WebFonts still render weird on some systems).

**Comment by jedahan** [comment]
+1 for avoiding bikeshedding by using system fonts, until a suitable legal replacement is found

**Comment by archseer** [comment]
Just... get rid of it ASAP. The fonts have been there for 20 days now, and this issue open unresolved for 4 days. Believe me, the last thing you want is a DMCA takedown notice.

**Comment by spolu** [comment]
Decided to remplace by roboto. Will issue PRs

**Comment by spolu** [comment]
All occurences have been removed. Will update release binaries as well.
