### ISSUE TITLE
Crashes on startup (Mac OSX 10.9.2)

### ISSUE THREAD

**Issue by dwhly** [spolu/breach_core#81]
Process:         Breach [32153]
Path:            /Applications/Breach.app/Contents/MacOS/Breach
Identifier:      org.breach.Breach
Version:         ???
Code Type:       X86 (Native)
Parent Process:  launchd [153]
Responsible:     Breach [32153]
User ID:         502

Date/Time:       2014-07-10 17:48:54.486 -0700
OS Version:      Mac OS X 10.9.2 (13C64)
Report Version:  11
Anonymous UUID:  347A6F26-3AA8-C9AD-6C8F-97CF29ECEF52

Sleep/Wake UUID: 195CE1E9-C374-4473-B9A8-8D1376512B38

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/ExoBrowser Framework.framework/ExoBrowser Framework
  Referenced from: /Applications/Breach.app/Contents/MacOS/Breach
  Reason: no suitable image found.  Did find:
    /Applications/Breach.app/Contents/MacOS/../Frameworks/ExoBrowser Framework.framework/ExoBrowser Framework: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
    /Applications/Breach.app/Contents/MacOS/../Frameworks/ExoBrowser Framework.framework/ExoBrowser Framework: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00

Binary Images:
0x8fe17000 - 0x8fe49417  dyld (239.4) <2E655535-479B-3E48-ADD3-6278819CA38A> /usr/lib/dyld

**Comment by camelCaseD** [comment]
I'm running it on 10.9.2 without any problems. Have you tried redownloading it?

**Comment by spolu** [comment]
no update closing for now
