### ISSUE TITLE
Is it possible to script the right-click menu on a page?

### ISSUE THREAD

**Issue by dzrw** [spolu/breach_core#85]
For example, I'd like to add "Back", "Forward", and "Reload" options because I keep reaching for them out of habit.

**Comment by spolu** [comment]
Yes it's handled here:
https://github.com/breach/mod_strip/blob/master/lib/tabs.js#L475

Back/Forward should be added properly.

**Comment by spolu** [comment]
This belongs to http://github.com/breach/mod_strip

**Comment by spolu** [comment]
Answered
