### ISSUE TITLE
Add brew cask for breach

### ISSUE THREAD

**Issue by epower** [spolu/breach_core#89]
https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md

A brew cask would be great for adoption and updates on OSX.

**Comment by jedahan** [comment]
Looks like someone is already on it
https://github.com/caskroom/homebrew-cask/pull/5296

**Comment by vinkla** [comment]
This is implemented in caskroom/homebrew-cask#5296. This issue can now be closed.

**Comment by spolu** [comment]
I uess we can close this one then?

**Comment by spolu** [comment]
Thanks for taking care of this. This is awesome!
