### ISSUE TITLE
Some pages just give a blank screen when running under Yosemite

### ISSUE THREAD

**Issue by naknut** [spolu/breach_core#91]
If i try to navigate to www.reddit.com or www.facebook.com I just get a blank screen. Is there any way to get some debug output so I can get an idea of what the problem is?

**Comment by omegahm** [comment]
I had the same problem on Yosemite. I actually also tried exactly www.reddit.com and www.facebook.com. It works fine in Mavericks (10.9.4)

**Comment by naknut** [comment]
Oooh, i use Yosemite aswell. So that seems to be the problem then. I updated the issue label to further express that this only happens in Yosemite.

**Comment by zhiayang** [comment]
Additionally, some sites appear fine (http://www.youtube.com, http://forum.osdev.org), but again blank out once you scroll a little bit.

Also on Yosemite.

**Comment by spolu** [comment]
duplicate of #116
